### PR TITLE
Homework19

### PR DESCRIPTION
**Pull request by ElenaChurinova**
Verify that the notification displayed has the text, "Deleted playlist {playlist name}".

### CODE REVIEW

**Comment by Berichicko** [comment]
You got this problem, please correct it.

image

**HINT**

**Step 1**

Test error (red). This status is assigned to tests that caused an exception from the tested source code.

The tester needs to identify an issue in their code: Test error. This status is assigned to tests that trigger an exception in the tested source code.
In software testing, the "Test error" status is assigned to tests that trigger an exception in the tested source code. When a test case fails due to an unexpected exception being thrown during its execution, it is marked as a test error. This indicates that the code being tested has not handled the exception properly, and further investigation and debugging are required to address the issue.

This status indicates an error in the code and the tester must fix this error:

Test error_en


**Step 2**

**NoSuchElementException**  

**Verify the locator(or change locator):** As a first step, you ought to find out what kind of issue you are dealing with. Is the element still there and can't be found, or is it no longer present on the page? To do this, you can setup Selenium to not to close the browser after the test failure, and run the test. Once you get the exception, you can inspect the page that is open in the browser. Double-check that the locator being used is correct and up-to-date. Inspect the HTML source code to confirm that the locator uniquely identifies the target element on the page.

**Comment by ElenaChurinova** [comment]
I successfully passed my test and I played it in the class Homework19 and in the Gradle!!!! I don't understand why you have my test failed. I double checked everything and there is no any errors .
Screenshot 2024-07-29 at 00 50 00
Screenshot 2024-07-29 at 00 53 47

**Comment by Berichicko** [comment]
> I successfully passed my test and I played it in the class Homework19 and in the Gradle!!!! I don't understand why you have my test failed. I double checked everything and there is no any errors . Screenshot 2024-07-29 at 00 50 00 Screenshot 2024-07-29 at 00 53 47

OK Please, re-submit homework 19 for review

**Comment by Berichicko** [comment]
Hello,

I have checked your homework 19, and I wanted to let you know that you're doing great! Keep up the excellent work!
Best wishes from the HW team (Alex, [aliaksandr@testpro.io](mailto:aliaksandr@testpro.io))!

Thumbs-up-hand-with-crown-illustration-on-transparent-background-PNG

Quote


image

PS: Don't worry!

Using specific symbols, like ↵, can be unclear for other developers and make the code harder to maintain. I'm on Windows, so the version control system doesn't handle these symbols correctly.

Better this way:

image

AND

**You can use this extension for easy locator search.**

 Ranorex Selocity

Ranorex Selocity is a free extension for Chrome DevTools. It allows you to create unique selectors through a smart selector generator. Feedback is created, allowing you to locate your web page's elements in the most secure manner. https://www.ranorex.com/selocity/browser-extension/

For example 

image

Xpath cheatsheet https://devhints.io/xpath

**Pull request closed without merging**
