### PR TITLE
Homework 17

### PR DESCRIPTION
**Pull request by Pestrada72**
TestNG Overview

### CODE REVIEW

**Comment by Berichicko** [comment]
You got this problem, please correct it.

image

**HINT**

**Step 1**

**NoSuchElementException**  

1. Verify the locator: As a first step, you ought to find out what kind of issue you are dealing with. Is the element still there and can't be found, or is it no longer present on the page? To do this, you can setup Selenium to not to close the browser after the test failure, and run the test. Once you get the exception, you can inspect the page that is open in the browser. Double-check that the locator being used is correct and up-to-date. Inspect the HTML source code to confirm that the locator uniquely identifies the target element on the page.

image


**You can use this extension for easy locator search.**

 Ranorex Selocity

Ranorex Selocity is a free extension for Chrome DevTools. It allows you to create unique selectors through a smart selector generator. Feedback is created, allowing you to locate your web page's elements in the most secure manner. https://www.ranorex.com/selocity/browser-extension/

For example 

image

**Comment by Pestrada72** [comment]
TestNG Overview

**Comment by Berichicko** [comment]
Hello,

I have checked your homework 17, and I wanted to let you know that you're doing great! Keep up the excellent work!
Best wishes from the HW team (Alex, [aliaksandr@testpro.io](mailto:aliaksandr@testpro.io))!

804deb64dc406a20a75da05d91a1a69e

image

**My recommendations:**
Adding multiple arguments:
`--disable-notifications`: disabling notifications
`--remote-allow-origins=*`: allowing remote origins
`--incognito`: launching in incognito mode
`--start-maximized`: launching in maximized mode
`"excludeSwitches", new String[]{"enable-automation"} `: Disable notification Chrome is being controlled by automated test software in ChromeDriver
**These settings are enabled to simplify and improve the process of automated testing.**
_For example_
image

**Comment by Berichicko** [comment]
**I will try to help you how easy it is to find locators:**

**1) These steps describe the process of opening the developer console in the Google Chrome browser and making changes to the styles of a popover that appears when hovering over a specific element on a web page.**

For example

 `By.cssSelector("div.success.show")`

image

image

Browse to the desired page
1.	Open the dev console - F12 on Windows/Linux or option + ⌘ + J on macOS
2.	Select the Sources tab in chrome inspector
3.	In the web browser window, hover over the desired element to initiate the popover
4.	Hit F8 on Windows/Linux (or fn + F8 on macOS or  CTRL+\) while the popover is showing. If you have clicked anywhere on the actual page F8 will do nothing. Your last click needs to be somewhere in the inspector, like the sources tab
5.	Go to the Elements tab in inspector
6.	Find your popover (it will be nested in the trigger element's HTML)
7.	Have fun modifying the CSS
8.	https://www.howtogeek.com/663950/what-your-function-keys-do-in-chrome-devtools/

**Pull request closed without merging**
